### ISSUE TITLE
Make the whole app dark themed

### ISSUE THREAD

**Issue by nickago** [WhiteHatCP/wrath-ctf-framework#10]
As I was attempting to implement @DeltaHeavy's comment in #9, I realized it would have to be put off for a later PR because the rest of the app is light-themed. This issue is less to report something and more put out a potential PR for the community to do.

**Comment by nickfrostatx** [comment]
Did somebody say dark theme?

![Dark theme](https://i.kinja-img.com/gawker-media/image/upload/s--QOakniH8--/c_fit,fl_progressive,q_80,w_636/18edh1z146cjapng.png)

If we're doing a CSS redesign, maybe we can drop the Bootstrap dependency?
