### ISSUE TITLE
Robots.txt and Humans.txt don't resolve

### ISSUE THREAD

**Issue by nickago** [WhiteHatCP/wrath-ctf-framework#12]
@DeltaHeavy noticed that /robots.txt doesn't resolve, but /static/robots.txt does. Need to consult with @nickfrostatx on how to add the robots in a Blueprints friendly way.

**Comment by nickfrostatx** [comment]
So `"/static"` is just the default static URL path in Flask. We can configure that that to be just `""` on production, and `/robots.txt` will point at the right file on prod. At least, that's how it was set up during the iFixit deployment.

**Comment by nickago** [comment]
Resolving this as an issue for deployment, not so much for the general repository
