### ISSUE TITLE
Tests are really bad

### ISSUE THREAD

**Issue by nickfrostatx** [WhiteHatCP/wrath-ctf-framework#47]
I'm sorry about [`tests/test_frontend.py`](https://github.com/WhiteHatCP/wrath-ctf-framework/blob/1b149a40bdb4c68bfd181ae2fe8b0d828da75506/tests/test_frontend.py#L23-L85).

It's one giant function that rolls through use cases on the app and asserts things along the way. It's hard to understand it, and even harder to test new things.

This file should be a bunch of distinct test cases, that each test one piece of logic. If we have small tests with some helper functions, then it should be easy to add new tests when we change the app.

**Comment by atti1a** [comment]
Closed by #51
