### ISSUE TITLE
Should we remove prereqs?

### ISSUE THREAD

**Issue by nickfrostatx** [WhiteHatCP/wrath-ctf-framework#50]
Problem prerequisites might be unnecessary.

They're only useful for an OTW-style CTF, yet they make our problem logic more complicated. For example, there's an N+1 on `/challenges/` because of prereq fetching, even if there are no prereqs in the CTF.

In the interest of simplicity, I think we would benefit from removing the feature.

**Comment by nickfrostatx** [comment]
@DeltaHeavy @atti1a

**Comment by atti1a** [comment]
While I agree that removing N+1 queries from things is good, there have been legitimate uses for prereqs in the past (hardware/lockpicking in the Triathalon). Does SQLAlchemy not take care of those optimizations for us?
